export enum ParameterEnum {
    DELAY = "DELAY",
    ADDRESS = "ADDRESS",
    WHATSAPP = "WHATSAPP",
    EMAIL = "EMAIL",
    PHONE = "PHONE",
    INSTAGRAM = "INSTAGRAM",
    SCHEDULES = "SCHEDULES",
    UPDATE_MENU = "UPDATE MENU"
}